-- DO NOT RUN THIS FILE.
-- Filename starts with "_" so `npm run db:migrate` ignores it.
--
-- Stage A migrations (run in this order only):
--   1. 20260726_m0_auth_rls.sql
--   2. 20260726_m0c_invite_audit.sql
--   3. 20260726_m1_billing_quota.sql
--   4. 20260726_m1b_plan_team_quota_atomic.sql
--
-- Preferred:
--   npm run db:migrate
-- or:
--   npm run db:open-sql
--
-- Guide: scripts/MIGRATION-GUIDE.md
SELECT 1;
